Swap state machine
farcaster-project/farcaster-node pull request #804
Opened 2022-12-04 11:15 UTC by TheCharlatan

2022-12-13 20:27 UTC, h4sh3d commented on src/swapd/runtime.rs
> +                self.log_trace("Watch height monero");
General comment about these log trace, isn't the trace level too low? IMO these messages could be at the debug level and trace is only used when printing array of bytes, big hex strings, etc.

2022-12-14 20:25 UTC, h4sh3d commented on src/swapd/runtime.rs
> +                self.log_trace("Watch height monero");
Resolved by async discussion with @TheCharlatan

2022-12-14 20:40 UTC, TheCharlatan reviewed
ACK 693c21583f01cd7992da70013b41aca17eec2cb7

2022-12-14 20:42 UTC, Lederstrumpf requested changes
tACK @a5ebfe5c8cce9e65d1ff4bc7f8bfa1c3b85d4aea

This is an *excellent* refactor and was a joy to review, kudos @TheCharlatan! It's turned a lot of logic that was previously wired in a twisted mess sequential and clear: the protocol screams its identity from the code now and can be reasoned about. I've opened up issues #828, #833, #834, and #835 to track issues I ran into during the review that make more sense to address in follow-up PRs than to integrate here.

Stats:
``` bash
[2022-12-12T04:04:23Z INFO  farcaster_node::farcasterd::stats] Swapped(4630) | Refunded(35) / Punished(0) | Aborted(0) | Initialized(4688) / AwaitingFundingXMR(0) / AwaitingFundingBTC(0) / FundedXMR(2332) / FundedBTC(2316) / FundingCanceledXMR(28) / FundingCanceledBTC(0)
```

2022-12-14 20:43 UTC, Lederstrumpf approved these changes
tACK @a5ebfe5c8cce9e65d1ff4bc7f8bfa1c3b85d4aea

This is an *excellent* refactor and was a joy to review, kudos @TheCharlatan! It's turned a lot of logic that was previously wired in a twisted mess sequential and clear: the protocol screams its identity from the code now and can be reasoned about. I've opened up issues #828, #833, #834, and #835 to track issues I ran into during the review that make more sense to address in follow-up PRs than to integrate here.

Stats:
``` bash
[2022-12-12T04:04:23Z INFO  farcaster_node::farcasterd::stats] Swapped(4630) | Refunded(35) / Punished(0) | Aborted(0) | Initialized(4688) / AwaitingFundingXMR(0) / AwaitingFundingBTC(0) / FundedXMR(2332) / FundedBTC(2316) / FundingCanceledXMR(28) / FundingCanceledBTC(0)
```

2022-12-14 20:45 UTC, h4sh3d approved these changes

2022-12-14 20:45 UTC, merged